# Generated by Django 5.2.1 on 2025-05-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('sdt', models.CharField(blank=True, max_length=10, null=True)),
                ('gioiTinh', models.CharField(choices=[('NAM', 'NAM'), ('NỮ', 'NỮ'), ('KHÁC', 'KHÁC')], max_length=5)),
                ('ngaySinh', models.DateField(blank=True, null=True)),
                ('diaChi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'User')], default=2)),
            ],
        ),
    ]
