# Generated by Django 5.2.1 on 2025-05-16 04:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('sdt', models.CharField(blank=True, max_length=10)),
                ('gioiTinh', models.CharField(choices=[('NAM', 'NAM'), ('NỮ', 'NỮ'), ('KHÁC', 'KHÁC')], default='NAM', max_length=5)),
                ('ngaySinh', models.DateField(blank=True)),
                ('diaChi', models.TextField(blank=True)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='avatar')),
                ('role', models.CharField(choices=[('1', 'admin'), ('2', 'user')], default='2', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
