# Generated by Django 5.2.1 on 2025-05-16 05:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diaChi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ngaySinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sdt',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
