# Generated by Django 5.2.1 on 2025-05-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Superuser'), ('2', 'Admin'), ('3', 'User')], default='3', max_length=1),
        ),
    ]
