# Generated by Django 5.2.1 on 2025-05-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_user_avatar_alter_user_diachi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diaChi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sdt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
