# Generated by Django 5.2.1 on 2025-05-27 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiVaccine',
            fields=[
                ('ma_loai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('ma_vaccine', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ten_vc', models.CharField(max_length=100)),
                ('tuoi', models.IntegerField()),
                ('nsx', models.DateField()),
                ('hsd', models.DateField()),
                ('nguon_goc', models.CharField(max_length=100)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loai_vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='courses.loaivaccine')),
            ],
        ),
    ]
