# Generated by Django 5.2.1 on 2025-05-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_loaivaccine_vaccine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaivaccine',
            old_name='ma_loai',
            new_name='maLoai',
        ),
        migrations.RenameField(
            model_name='loaivaccine',
            old_name='ten_loai',
            new_name='tenLoai',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='loai_vaccine',
            new_name='loaiVaccine',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='ma_vaccine',
            new_name='maVaccine',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='nguon_goc',
            new_name='nguoGoc',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='ten_vc',
            new_name='tenVc',
        ),
    ]
