# Generated by Django 5.2.1 on 2025-05-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_ma_loai_loaivaccine_maloai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='hsd',
            new_name='HSD',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='nsx',
            new_name='NSX',
        ),
    ]
