# Generated by Django 5.2.1 on 2025-05-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_hsd_vaccine_hsd_rename_nsx_vaccine_nsx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='nguoGoc',
            new_name='nguonGoc',
        ),
    ]
