# Generated by Django 5.2.1 on 2025-05-28 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_nguogoc_vaccine_nguongoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='gioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuong', models.IntegerField()),
                ('maUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gio_hang', to=settings.AUTH_USER_MODEL)),
                ('maVaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gio_hang', to='courses.vaccine')),
            ],
        ),
    ]
