# Generated by Django 5.2.1 on 2025-05-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_giohang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giohang',
            old_name='maUser',
            new_name='EmailUser',
        ),
    ]
