# Generated by Django 5.2.1 on 2025-05-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_mauser_giohang_emailuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giohang',
            old_name='EmailUser',
            new_name='maUser',
        ),
    ]
