# Generated by Django 5.2.1 on 2025-05-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_giohang_soluong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giohang',
            old_name='maUser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='giohang',
            old_name='maVaccine',
            new_name='vaccine',
        ),
    ]
