# Generated by Django 5.2.1 on 2025-05-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_rename_mauser_giohang_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='tuoi',
        ),
        migrations.AddField(
            model_name='loaivaccine',
            name='tuoi',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='soMui',
            field=models.IntegerField(default=2),
        ),
    ]
