# Generated by Django 5.2.1 on 2025-05-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_vaccine_tuoi_loaivaccine_tuoi_vaccine_somui'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='thongTin',
            field=models.TextField(default=' '),
        ),
    ]
