# Generated by Django 5.2.1 on 2025-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_vaccine_thongtin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='soMui',
        ),
        migrations.AddField(
            model_name='loaivaccine',
            name='soMui',
            field=models.IntegerField(default=2),
        ),
    ]
