# Generated by Django 5.2.1 on 2025-06-03 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_loaivaccine_somui_alter_loaivaccine_tuoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giohang',
            name='soLuong',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DonDangKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayDangKy', models.DateField(auto_now_add=True)),
                ('nguoiDangKy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_dang_ky', to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='NguoiTiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ngaySinh', models.DateField()),
                ('gioiTinh', models.CharField(choices=[('NAM', 'NAM'), ('NỮ', 'NỮ'), ('KHÁC', 'KHÁC')], default='NAM', max_length=5)),
                ('sdt', models.CharField(max_length=10)),
                ('diaChi', models.TextField()),
                ('nguoiTao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_tiem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonTiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trangThai', models.IntegerField(choices=[(1, 'Chưa tiêm'), (2, 'Đã tiêm'), (3, 'Đã hủy')], default=1)),
                ('donDangKy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_tiem', to='courses.dondangky')),
                ('nguoiTiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_tiem', to='courses.nguoitiem')),
            ],
        ),
    ]
