# Generated by Django 5.2.1 on 2025-06-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_dontiem_ngaytiem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dontiem',
            name='ngayTiem',
            field=models.DateField(),
        ),
    ]
